# Generated by Django 4.2.13 on 2026-06-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shop_address_alter_shop_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(blank=True, choices=[('supermarket', 'Supermarket'), ('stationary', 'Stationary'), ('quickcommerce', 'Quick Commerce'), ('grocery', 'Grocery')], max_length=50),
        ),
    ]
