# Generated by Django 4.2.13 on 2026-06-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_address_latitude_alter_address_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
