# Generated by Django 4.2.13 on 2026-06-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_delivery_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for Delivery'), ('delivery_confirmation_pending', 'Waiting Customer Confirmation'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=40),
        ),
    ]
